name       : haskell-cmark-gfm
version    : 0.1.3
release    : 1
source     :
    - https://hackage.haskell.org/package/cmark-gfm-0.1.3/cmark-gfm-0.1.3.tar.gz : 731cb392e4edfd18d0dae709904791610588e6770934e5112cbdd5e6f3d271ba
license    : BSD-3-Clause
component  : programming.haskell
summary    : Haskell bindings to libcmark-gfm GitHub Flavored Markdown parser 
description: |
    This package provides Haskell bindings for libcmark-gfm, the reference parser for GitHub Flavored Markdown, a fully specified variant of Markdown. It includes sources for libcmark-gfm (0.28.0) and does not require prior installation of the C library.
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-text
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
