name       : haskell-cmark-gfm
version    : 0.2.1
release    : 2
source     :
    - https://hackage.haskell.org/package/cmark-gfm-0.2.1/cmark-gfm-0.2.1.tar.gz : 4330e20dcdf4ca2586585298093d2c514d4b59c208bb38283219a8f3726470e1
license    : BSD-3-Clause
component  : programming.haskell
summary    : Haskell bindings to libcmark-gfm GitHub Flavored Markdown parser
description: |
    This package provides Haskell bindings for libcmark-gfm, the reference parser for GitHub Flavored Markdown, a fully specified variant of Markdown. It includes sources for libcmark-gfm (0.28.0) and does not require prior installation of the C library.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
